In [1]:
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\shank\Desktop\Diabetics\diabetes_prediction_dataset (1).csv")
df

gender   age  hypertension  heart_disease smoking_history    bmi  \
0      Female  80.0             0              1           never  25.19   
1      Female  54.0             0              0         No Info  27.32   
2        Male  28.0             0              0           never  27.32   
3      Female  36.0             0              0         current  23.45   
4        Male  76.0             1              1         current  20.14   
...       ...   ...           ...            ...             ...    ...   
99995  Female  80.0             0              0         No Info  27.32   
99996  Female   2.0             0              0         No Info  17.37   
99997    Male  66.0             0              0          former  27.83   
99998  Female  24.0             0              0           never  35.42   
99999  Female  57.0             0              0         current  22.43   

       HbA1c_level  blood_glucose_level  diabetes  
0              6.6                  140         0  
1              6.6                   80         0  
2              5.7                  158         0  
3              5.0                  155         0  
4              4.8                  155         0  
...            ...                  ...       ...  
99995          6.2                   90         0  
99996          6.5                  100         0  
99997          5.7                  155         0  
99998          4.0                  100         0  
99999          6.6                   90         0  

[100000 rows x 9 columns]

## EDA

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   gender               100000 non-null  object 
 1   age                  100000 non-null  float64
 2   hypertension         100000 non-null  int64  
 3   heart_disease        100000 non-null  int64  
 4   smoking_history      100000 non-null  object 
 5   bmi                  100000 non-null  float64
 6   HbA1c_level          100000 non-null  float64
 7   blood_glucose_level  100000 non-null  int64  
 8   diabetes             100000 non-null  int64  
dtypes: float64(3), int64(4), object(2)
memory usage: 6.9+ MB


In [6]:
#null value checking
df.isnull().sum() #- no null values

gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

In [8]:
#duplicates checking
df.duplicated().sum()

3854

In [9]:
#for now we are only keeping 1st occurance of the duplicates
df.drop_duplicates(keep ="first",inplace = True)

In [10]:
df.duplicated().sum() #we cleared duplicates

0

In [11]:
df.shape

(96146, 9)

In [12]:
df.columns

Index(['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history',
       'bmi', 'HbA1c_level', 'blood_glucose_level', 'diabetes'],
      dtype='object')

In [14]:
#spelling check and encoding of the data
df["gender"].unique() , df["smoking_history"].unique()

(array(['Female', 'Male', 'Other'], dtype=object),
 array(['never', 'No Info', 'current', 'former', 'ever', 'not current'],
       dtype=object))

In [15]:
from sklearn.preprocessing import OrdinalEncoder
enc = OrdinalEncoder()
df["gender"] = enc.fit_transform(df[["gender"]])
df["smoking_history"] = enc.fit_transform(df[["smoking_history"]])


In [16]:
df["gender"].unique() , df["smoking_history"].unique() #converted into numerical value

(array([0., 1., 2.]), array([4., 0., 1., 3., 2., 5.]))

In [17]:
df.head()

gender   age  hypertension  heart_disease  smoking_history    bmi  \
0     0.0  80.0             0              1              4.0  25.19   
1     0.0  54.0             0              0              0.0  27.32   
2     1.0  28.0             0              0              4.0  27.32   
3     0.0  36.0             0              0              1.0  23.45   
4     1.0  76.0             1              1              1.0  20.14   

   HbA1c_level  blood_glucose_level  diabetes  
0          6.6                  140         0  
1          6.6                   80         0  
2          5.7                  158         0  
3          5.0                  155         0  
4          4.8                  155         0

In [31]:
df["HbA1c_level"].describe()

count    96146.000000
mean         5.532609
std          1.073232
min          3.500000
25%          4.800000
50%          5.800000
75%          6.200000
max          9.000000
Name: HbA1c_level, dtype: float64

## Model Building

In [19]:
#defining x and y
x=df.iloc[:,:-1] #independent
y = df["diabetes"] #depenent

In [21]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [22]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

model = DecisionTreeClassifier().fit(x_train,y_train)
y_pred =model.predict(x_test)


In [23]:

confusion_matrix(y_test,y_pred)

array([[25456,   785],
       [  723,  1880]], dtype=int64)

In [24]:
accuracy_score(y_test,y_pred)

0.9477187630009707

In [25]:
print(classification_report(y_test,y_pred))


              precision    recall  f1-score   support

           0       0.97      0.97      0.97     26241
           1       0.71      0.72      0.71      2603

    accuracy                           0.95     28844
   macro avg       0.84      0.85      0.84     28844
weighted avg       0.95      0.95      0.95     28844



In [26]:
import numpy as np

In [27]:
shankari = np.array([[0,24,0,0,4,25.52,5.9,125]])
shankari_pred = model.predict(shankari)


c:\Users\shank\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


In [28]:
shankari_pred #like this we can predict if the patient has diabetes or not

array([0], dtype=int64)

In [29]:
import pickle
pickle.dump(model,open("diabetes.pkl","wb"))
